---
- name: Deploy E-Commerce App on AWS EC2
  hosts: webservers
  become: yes

  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Install pip (for AWS CLI if needed)
      yum:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Pull E-Commerce app image
      docker_image:
        name: yourdockerhubusername/ecommerce-app
        source: pull

    - name: Run E-Commerce app container
      docker_container:
        name: ecommerce-app
        image: yourdockerhubusername/ecommerce-app
        state: started
        ports:
          - "80:5000"
        restart_policy: always
